// requires "k-prelude.k"
requires "kast.md"
requires "domains.md"
// requires "builtins/list.k"
// requires "builtins/map.k"
// requires "builtins/set.k"
// requires "builtins/mint.k"
// requires "io/io.k"
//requires "modules/substitution.k"
//requires "modules/k-functional-visitor.k"

module JS-PRELUDE

// imports BUILTIN-HOOKS
imports K
imports LIST
imports MAP
imports SET
imports MINT
imports K-IO
//imports SUBSTITUTION
//imports K-FUNCTIONAL-VISITOR

endmodule
